---
title: "STAT0006 ICA 3"
author: 'Student numbers: 123456789, 123456789, 123456789, 123456789'
subtitle: Group XXX
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

### Introduction to the data

``` {r, echo=FALSE}
#setwd("~/Downloads/Everything you need for ICA 3-20221231")
# importing data set
ic <- read.csv('ice_creams.csv')

# identifying and removing NA values
which(is.na(ic), arr.ind = TRUE)
ic <- ic[-c(271,249,177),]

# summary of ic
summary(ic)

```
```{r load-packages, include=FALSE}
library(scales)
```


```{r echo=FALSE, warning=FALSE,,  fig.height=4, fig.width=10, fig.align='center'}

par(mfrow=c(1,2))

boxplot(ic$sales~ic$brand, ylab = "Sales (no of ice creams)", xlab = "Brand" , col = "grey", main = "Sales & Type of Brand being counted",cex.axis = 0.8)
points(c(mean(ic$sales[ic$brand=="BrandA"]), 
         mean(ic$sales[ic$brand=="BrandB"]),
         mean(ic$sales[ic$brand=="BrandC"])),
       pch=16, cex=1.5, col="orange")


boxplot(ic$sales~ic$holiday, ylab = "Sales (no of ice creams)", xlab = "Y/N Bank Holiday" ,col = "grey", main = "Sales & Whether there is Bank Holiday", names = c(" ", " "), cex.axis = 0.8)
points(c(mean(ic$sales[ic$holiday=="N"]), 
         mean(ic$sales[ic$holiday=="Y"])),
         pch=16, cex=1.5, col = "orange")
axis(1,at = c(1,2), labels = c("Without Bank Holiday", "With Bank Holiday"),cex.axis = 0.8)

```

```{r echo=FALSE, warning=FALSE,,  fig.height=4, fig.width=10, fig.align='center'}

par(mfrow=c(1,2), mar = c(3,3,2,2))

boxplot(ic$sales~ic$promotion, ylab = "Sales (no of ice creams)", xlab = "Y/N Promotion", col = "grey", main = "Sales & Whether there is Promotion", names = c("Without Promotion", "With Promotion"), cex.axis = 0.8)
points(c(mean(ic$sales[ic$promotion=="N"]),
         mean(ic$sales[ic$promotion=="Y"])),
         pch=16, cex=1.5, col = "orange")

boxplot(ic$sales~ic$store_type, ylab = "Sales (no of ice creams)", xlab = "Sise of Store", col = "grey", main = "Sales & Size of store", cex.axis = 0.8)
points(c(mean(ic$sales[ic$store_type=="Large"]),
         mean(ic$sales[ic$store_type=="Medium"]),
         mean(ic$sales[ic$store_type=="Small"])),
       pch=16, cex=1.5, col="orange")

```

```{r echo=FALSE, warning=FALSE,,  fig.height=4, fig.width=10, fig.align='center'}

par(mar = c(2,2,2,2))

boxplot(ic$sales~ic$year, ylab = "Sales (no of ice creams)", xlab = "Year", col = "grey", main = "Sales between 2018 and 2022", cex.axis = 0.8)
points(c(mean(ic$sales[ic$year== 2018]),
        mean(ic$sales[ic$year== 2019]),
        mean(ic$sales[ic$year== 2020]),
        mean(ic$sales[ic$year== 2021]),
        mean(ic$sales[ic$year== 2022])),
       pch=16, cex=1.5, col="orange")

boxplot(ic$sales~ic$brand_competitors, ylab = "Sales (no of ice creams)", xlab = "No of Competitors", col = "grey", main = "Sales & No of Competitors", cex.axis = 0.8)
points(c(mean(ic$sales[ic$brand_competitors== 3]),
        mean(ic$sales[ic$brand_competitors== 4]),
        mean(ic$sales[ic$brand_competitors== 5]),
        mean(ic$sales[ic$brand_competitors== 6]),
        mean(ic$sales[ic$brand_competitors== 7]),
        mean(ic$sales[ic$brand_competitors== 8]),
        mean(ic$sales[ic$brand_competitors== 9])),
       pch=16, cex=1.5, col="orange")

```

sales vs brand: there is relationship


```{r echo=FALSE, warning=FALSE,,  fig.height=4, fig.width=10, fig.align='center'}

par(mfrow=c(1,2))

plot(ic$sales~sqrt(ic$distance), ylab = "Sales (no of ice creams)", xlab = "Distance", col = "grey", main = "Sales & Distance", pch = 20 ,cex.axis = 0.8)

plot(ic$sales~I((ic$milk)^2), ylab = "Sales (no of ice creams)", xlab = "Price of Milk", col = "grey", main = "Sales & Milk",pch = 20 ,cex.axis = 0.8) 

```

```{r echo=FALSE, warning=FALSE,,  fig.height=4, fig.width=10, fig.align='center'}

par(mfrow=c(1,3))

plot(ic$sales~ic$temperature, ylab = "Sales (no of ice creams)", xlab = "Average Weekly Temperature", col = "grey", main = "Sales & Temperature", pch = 20 ,cex.axis = 0.8)

plot(ic$sales~I((ic$wind)^-1), ylab = "Sales (no of ice creams)", xlab = "Average Weekly Speed of Wind", col = "grey", main = "Sales & Wind", pch = 20 ,cex.axis = 0.8)

#plot(ic$sales~sqrt(1.8 * ic$temperature + 32), ylab = "Sales (no of ice creams)", xlab = "Average Weekly Temperature", col = "grey", main = "Sales & Temperature", pch = 20 ,cex.axis = 0.8)

```

```{r  include=TRUE,echo=FALSE}

M <- ic[c("sales","distance", "milk", "temperature", "wind")]

```

```{r  include=TRUE, echo=FALSE, warning=FALSE, fig.height=5, fig.width=10, fig.align='center'}
panel.cor <- function(x, y){
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    r <- round(cor(x, y), digits=2)
    txt <- paste0("r = ", r)
    cex.cor <- 0.8/strwidth(txt)
    text(0.5, 0.5, txt)
}
# Customize upper panel
upper.panel<-function(x, y){
  points(x,y, pch = "." , col = "dark blue")
}
# Create the plots
pairs(M, 
      lower.panel = panel.cor,
      upper.panel = upper.panel)
```


```{r}
# PLOT OF SALES & DISTANCE, VARY ACROSS DIFFERENT CATEGORICAL VARIABLE. SIMILAR TO ICA 1
#legend to show the color representing

plot(ic$sales~ic$distance, ylab = "Sales (no of ice creams)", xlab = "Distance", main = "Sales & Distance (INTERACTION - brand)", pch = 20, col = factor(ic$brand))
legend("topleft",legend=c("BrandA","BrandB","BrandC"),col = unique(factor(ic$brand)), pch=20)

plot(ic$sales~ic$distance, ylab = "Sales (no of ice creams)", xlab = "Distance", main = "Sales & Distance (INTERACTION - brand_comp)", pch = 20, col = factor(ic$brand_competitors))
legend("topleft",legend=unique(factor(ic$brand_competitors)),col = unique(factor(ic$brand_competitors)), pch=20)


plot(ic$sales~ic$distance, ylab = "Sales (no of ice creams)", xlab = "Distance", main = "Sales & Distance (INTERACTION - holiday)", pch = 20, col = factor(ic$holiday))
legend("topleft",legend=unique(factor(ic$holiday)),col = unique(factor(ic$holiday)), pch=20)


plot(ic$sales~ic$distance, ylab = "Sales (no of ice creams)", xlab = "Distance", main = "Sales & Distance (INTERACTION - promotion)", pch = 20, col = factor(ic$promotion))
legend("topleft",legend=unique(factor(ic$promotion)),col = unique(factor(ic$promotion)), pch=20)


plot(ic$sales~ic$distance, ylab = "Sales (no of ice creams)", xlab = "Distance", main = "Sales & Distance (INTERACTION - store_type)", pch = 20, col = factor(ic$store_type))
legend("topleft",legend=unique(factor(ic$store_type)),col = unique(factor(ic$store_type)), pch=20)


plot(ic$sales~ic$distance, ylab = "Sales (no of ice creams)", xlab = "Distance", main = "Sales & Distance (INTERACTION - year)", pch = 20, col = factor(ic$year))
legend("topleft",legend=unique(factor(ic$year)),col = unique(factor(ic$year)), pch=20)


```
```{r}
# PLOT OF SALE & TEMPERATURE, VARY ACROSS DIFFERENT CATEGORICAL VARIABLE. SIMILAR TO ICA 1

plot(ic$sales~log(3*ic$temperature + 37), ylab = "Sales (no of ice creams)", xlab = "Average Weekly Temperature", main = "Sales & Temperature (INTERACTION - brand)", pch = 20, col = factor(ic$brand))
legend("topleft",legend=unique(factor(ic$brand)),col = unique(factor(ic$brand)), pch=20)

plot(ic$sales~log(3*ic$temperature + 37), ylab = "Sales (no of ice creams)", xlab = "Average Weekly Temperature", main = "Sales & Temperature (INTERACTION - brand_comp)", pch = 20, col = factor(ic$brand_competitors))
legend("topleft",legend=unique(factor(ic$brand_competitors)),col = unique(factor(ic$brand_competitors)), pch=20)

plot(ic$sales~log(3*ic$temperature + 37), ylab = "Sales (no of ice creams)", xlab = "Average Weekly Temperature", main = "Sales & Temperature (INTERACTION - holiday)", pch = 20, col = factor(ic$holiday))
legend("topleft",legend=unique(factor(ic$holiday)),col = unique(factor(ic$holiday)), pch=20)

plot(ic$sales~log(3*ic$temperature + 37), ylab = "Sales (no of ice creams)", xlab = "Average Weekly Temperature", main = "Sales & Temperature (INTERACTION - promotion)", pch = 20, col = factor(ic$promotion))
legend("topleft",legend=unique(factor(ic$promotion)),col = unique(factor(ic$promotion)), pch=20)

plot(ic$sales~log(3*ic$temperature + 37), ylab = "Sales (no of ice creams)", xlab = "Average Weekly Temperature", main = "Sales & Temperature (INTERACTION - store_type)", pch = 20, col = factor(ic$store_type))
legend("topleft",legend=unique(factor(ic$store_type)),col = unique(factor(ic$store_type)), pch=20)

plot(ic$sales~log(3*ic$temperature + 37), ylab = "Sales (no of ice creams)", xlab = "Average Weekly Temperature", main = "Sales & Temperature (INTERACTION - year)", pch = 20, col = factor(ic$year))
legend("topleft",legend=unique(factor(ic$year)),col = unique(factor(ic$year)), pch=20)


```



```{r include = TRUE}
#MODEL 1 INCLUDES ALL COVARIATES

model1 <- lm(ic$sales ~ 
               ic$brand
              +ic$brand_competitors
              +ic$holiday
              +ic$year
              +ic$promotion
              +ic$store_type
              +ic$temperature
              +ic$wind
              +ic$distance
              +ic$milk, data = ic)
summary(model1)
```

```{r include = TRUE}
#MODEL 2 REMOVED MILK AND WIND AND YEAR, ADDED INTERACTION

model2 <- lm(ic$sales ~ 
               ic$brand
              # +ic$brand_competitors
              +ic$holiday
              +ic$promotion
              +ic$store_type
              +ic$temperature
              +ic$distance
              , data = ic)
summary(model2)


#THE R-SQUARE INCREASED A BIT BUT THIS DOESNT MEAN MUCH, ALTHOUGH MAYBE A GOOD SIGN?


```


```{r}
# MODEL R ADD NEW INTERACTION TERMS, ATTEMPTED TO TRANSFORM TEMPERATURE (FROM C TO F THEN SQRT, BUT NOT VERY SUCCESSFUL). ANY OTHER TRANSFORMATIONS?

# t_temperature <- sqrt(1.8 * ic$temperature + 32)

model3 <- lm(ic$sales~ 
              +ic$temperature
              +ic$promotion
              # +ic$distance * ic$brand
              +ic$distance * ic$store_type
              +ic$store_type * ic$brand, data = ic)
summary(model3)


```


```{r}
model4 <- lm(sqrt(ic$sales)~ 
               ic$brand
              +ic$distance
              +ic$store_type
              +ic$temperature
              +ic$promotion
              +ic$distance * ic$brand
              +ic$distance * ic$store_type
              +ic$store_type*ic$brand, data = ic)
summary(model4)


```


```{r include = TRUE}
ic_rev <- subset(ic, ic$sales>200)
model5 <- lm(sales~ 
               brand
              +distance
              +store_type
              +temperature
              +promotion
              +distance * brand
              +distance * store_type
              +store_type * brand, data = ic_rev)
summary(model5)
```


```{r include = TRUE}
# CODE FOR BOX COX TRANSFORMATION FROM JENI. WE COULD USE THIS TO CHECK FOR POTENTIAL TRANSFORMATION ON Y

plot(hatvalues(model3), type="h", ylab="Leverage", xlab="Observation")
#Mean leverage is p/n = 16/311 = 0.0514
abline(a=16/311, b=0, lty=3, col="black")
#Twice the average leverage:
abline(a=2*16/311, b=0, lty=3,col="blue")
```

```{r, fig.width=14, fig.height=10, echo = FALSE}
par(mfrow=c(3,2))

predicted1 <- fitted(model1)
plot(ic$sales~predicted1, xlab = "Predicted sales", ylab = "Observed sales", xlim = c(0,2500), main = "Model 1", pch = 16, col=alpha("darkblue",0.6))
abline(a=0, b=1, col = "red")
grid(nx = NULL, ny = NULL,
     lty = 2,      # Grid line type
     col = "gray", # Grid line color
     lwd = 1)      # Grid line width

predicted2 <- fitted(model2)
plot(ic$sales~predicted2, xlab = "Predicted sales", ylab = "Observed sales", xlim = c(0,2500), main = "Model 2", pch = 16, col=alpha("darkblue",0.6))
abline(a=0, b=1, col = "red")
grid(nx = NULL, ny = NULL,
     lty = 2,      # Grid line type
     col = "gray", # Grid line color
     lwd = 1)      # Grid line width

predicted3 <- fitted(model3)
plot(ic$sales~predicted3, xlab = "Predicted sales", ylab = "Observed sales", xlim = c(0,2500), main = "Model 3", pch = 16, col=alpha("darkblue",0.6))
abline(a=0, b=1, col = "red")
grid(nx = NULL, ny = NULL,
     lty = 2,      # Grid line type
     col = "gray", # Grid line color
     lwd = 1)      # Grid line width

predicted4 <- fitted(model4)
plot(ic$sales~I(predicted4^2), xlab = "Predicted sales", ylab = "Observed sales", xlim = c(0,2500), main = "Model 4", pch = 16, col=alpha("darkblue",0.6))
abline(a=0, b=1, col = "red")
grid(nx = NULL, ny = NULL,
     lty = 2,      # Grid line type
     col = "gray", # Grid line color
     lwd = 1)      # Grid line width

predicted5 <- fitted(model5)
plot(ic_rev$sales~predicted5, xlab = "Predicted sales", ylab = "Observed sales", xlim = c(0,2500), main = "Model 5", pch = 16, col=alpha("darkblue",0.6))
abline(a=0, b=1, col = "red")
grid(nx = NULL, ny = NULL,
     lty = 2,      # Grid line type
     col = "gray", # Grid line color
     lwd = 1)      # Grid line width


```
```{r}
sum(predicted5<0)

```

```{r}
model5_stdres<-rstandard(model5)
qqnorm (model5_stdres, main="", ylab = "Standardised Residuals", xlab = "Quantiles of N(0,1)", pch = 20, col=alpha("darkblue",0.4))
qqline (model5_stdres)

model5_fitted<-fitted(model5)
plot(model5_fitted, model5_stdres, xlab="Fitted values", ylab="Standardised residuals", pch = 20, col=alpha("darkblue",0.4))
abline(a=0, b=0)

#normality of error the term
model3_stdres<-rstandard(model3)
qqnorm (model3_stdres, main="", ylab = "Standardised Residuals", xlab = "Quantiles of N(0,1)", pch = 20, col=alpha("darkblue",0.4))
qqline (model3_stdres)

#homoscedasticity of the error term
model3_fitted<-fitted(model3)
plot(model3_fitted, model3_stdres, xlab="Fitted values", ylab="Standardised residuals", pch = 20, col=alpha("darkblue",0.4))
abline(a=0, b=0)


#normality of error the term
model4_stdres<-rstandard(model4)
qqnorm (model4_stdres, main="", ylab = "Standardised Residuals", xlab = "Quantiles of N(0,1)", pch = 20, col=alpha("darkblue",0.4))
qqline (model4_stdres)

#homoscedasticity of the error term
model4_fitted<-fitted(model4)
plot(model4_fitted, model4_stdres, xlab="Fitted values", ylab="Standardised residuals", pch = 20, col=alpha("darkblue",0.4))
abline(a=0, b=0)
```

```{r}
#linearity
#par(mfrow=c(1,2))
plot(ic$temperature, model3_stdres, xlab="Temperature", ylab="Standardised residuals", pch = 20, col=alpha("darkblue",0.4))
abline(a=0, b=0)
plot(ic$distance, model3_stdres, xlab="Distance", ylab="Standardised residuals", pch = 20, col=alpha("darkblue",0.4))
abline(a=0, b=0)
```


```{r}
library(MASS)
boxcox(I(ic$sales+0.5) ~ 
               ic$brand
              +ic$brand_competitors
              +ic$distance
              +ic$holiday
              +ic$store_type
              +ic$temperature
              +ic$distance * ic$brand
              +ic$distance * ic$store_type
              +ic$store_type*ic$brand, data = ic)
```
```{r}
model5 <- lm(ic$sales~ 
               ic$brand
              +ic$brand_competitors
              +ic$distance
              +ic$store_type
              +ic$temperature
              +ic$promotion
              #+t_temperature
              +ic$store_type*ic$brand
              ,data=ic)

summary(model5)

```

### Model building



### Model checking for final chosen model

### Conclusion

### Discussion of limitations 
\
\
**Total word count:** insert your word count here.